### ISSUE TITLE
Measure requests to Prometheus endpoint

### ISSUE THREAD

**Issue by tomkerkhove** [prom-client-net/prom-client-httprequestdurations#21]
Measure requests to Prometheus endpoint so that it is included, because from what I'm seeing it isn't.

Would allow us to understand how fast we can serve metrics.

**Comment by phnx47** [comment]
I need time to research this

**Comment by phnx47** [comment]
@tomkerkhove Order is important for middlewares.
```
app.UsePrometheusRequestDurations(); // just add this before app.UsePrometheusServer();
app.UsePrometheusServer();
```

**Comment by tomkerkhove** [comment]
That does the trick, sorry 🤦‍♂️
